#!/bin/sh
device=`aselectdevice`
echo "use" $device
adb -s $device shell screencap -p /sdcard/screenshot.png
adb -s $device pull /sdcard/screenshot.png ./screenshot_`date "+%Y%m%d_%H%M%S"`.png
adb -s $device shell rm /sdcard/screenshot.png
open .
