#!/bin/sh
device=`adb devices|grep -v "List of devices"|awk 'NF==2{print $1}'|awk 'BEGIN{all=""} {all =$0"\n"all} END{if(NR==1) {print($0)} else{system("echo \""all "\"|peco") } }'`
echo "use" $device
adb -s $device shell screenrecord --verbose /sdcard/videoName.mp4 
adb pull /sdcard/videoName.mp4
adb shell exit
