#!/bin/sh
device=`aselectdevice`
echo "use" $device
target=`adb -s $device shell pm list package|sed -e 's/^package://g'|peco`
adb -s $device shell << EOS
run-as $target
cd shared_prefs
grep -n "" *
exit
exit
EOS
